
-- DROP TABLE IF EXISTS department cascade;
CREATE TABLE IF NOT EXISTS department (
    id      int4 not null generated by default as identity,
    department  varchar(255) not null,
    CONSTRAINT department_pkey primary key (id)
);

-- DROP TABLE IF EXISTS user_status cascade;
CREATE TABLE IF NOT EXISTS user_status (
    id      smallint not null generated by default as identity,
    status  varchar(100) not null,
    CONSTRAINT user_status_pkey primary key (id)
);

-- DROP TABLE IF EXISTS hobbies cascade;
CREATE TABLE IF NOT EXISTS hobbies (
    id      int4 not null generated always as identity,
    hobby   varchar(255) not null,
    CONSTRAINT hobbies_pkey primary key (id),
    CONSTRAINT hobbies_key UNIQUE(hobby)
);

-- DROP TABLE IF EXISTS users cascade;
CREATE TABLE IF NOT EXISTS users (
--     id      int4 not null generated always as identity,
    id      varchar(255) not null,
    name    varchar(255) not null,
    phone_no    varchar(20) not null,
    email       varchar(255) not null,
    status_id      smallint not null,
    department_id  int4,
    created_at   timestamp default CURRENT_TIMESTAMP,
    modified_at  timestamp,

    CONSTRAINT users_pkey primary key (id),
    CONSTRAINT user_status_fkey foreign key (status_id) references user_status (id) on delete RESTRICT on update cascade,
    CONSTRAINT user_department_fkey foreign key (department_id) references department (id) on delete set null on update cascade
);

-- DROP TABLE IF EXISTS user_hobbies;
CREATE TABLE IF NOT EXISTS user_hobbies (
    user_id       varchar(255) not null,
    hobby_id   int4 not null,

    CONSTRAINT user_hobbies_pkey primary key (user_id, hobby_id),
    CONSTRAINT user_hobbies_user_fkey foreign key (user_id) references users (id) on delete cascade on update cascade,
    CONSTRAINT user_hobbies_hobby_fkey foreign key (hobby_id) references hobbies (id) on delete cascade on update cascade
);


