server:
  port: 8080

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html

logging:
  level:
    root: ERROR
    '[org.springframework.web]': ERROR
    '[kr.datasolution.kdigital2023]': DEBUG

urls:
    scheme: http
    host: demo-bt
    port: 8088
    prefix: /api
    user:
        prefix: /user
        status: -status
    hobby:
        prefix: /hobby
    department:
        prefix: /department
